'use client';
import {useEffect,useMemo,useState} from 'react';
import {ShoppingBag,Search,MapPin,Clock,Truck,ChevronRight,Plus,Minus,X,Star,ShieldCheck,Heart} from 'lucide-react';

type Product={id:number;name:string;category:string;price:number;desc:string;image:string;rating:number};
const seed:Product[]=[
{id:1,name:'Lavash N1 Klassik',category:'Lavash',price:32000,desc:'Yumshoq non, shirali tovuq, sabzavot va maxsus sous.',image:'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=85',rating:4.9},
{id:2,name:'Lavash Max',category:'Lavash',price:42000,desc:'Kattaroq porsiya, ko‘proq go‘sht va pishloq.',image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85',rating:4.8},
{id:3,name:'Chicken Burger',category:'Burger',price:36000,desc:'Qarsildoq tovuq, yangi salat va N1 sousi.',image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',rating:4.8},
{id:4,name:'Cheese Burger',category:'Burger',price:39000,desc:'Mol go‘shti kotleti, cheddar, pomidor va sous.',image:'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=900&q=85',rating:4.7},
{id:5,name:'Chicken Box',category:'Setlar',price:45000,desc:'Tovuq bo‘laklari, kartoshka fri va sous.',image:'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=85',rating:4.9},
{id:6,name:'Fri & Sauce',category:'Gazaklar',price:18000,desc:'Oltindek qarsildoq fri va maxsus sous.',image:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',rating:4.6},
{id:7,name:'Coca-Cola 0.5L',category:'Ichimliklar',price:10000,desc:'Muzdek Coca-Cola.',image:'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=900&q=85',rating:4.8},
{id:8,name:'N1 Combo',category:'Setlar',price:59000,desc:'Lavash N1 + fri + ichimlik. Eng foydali tanlov.',image:'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=85',rating:5}
];
const money=(n:number)=>new Intl.NumberFormat('uz-UZ').format(n)+' so‘m';
export default function Home(){
 const [products,setProducts]=useState(seed),[cat,setCat]=useState('Barchasi'),[q,setQ]=useState(''),[cart,setCart]=useState<Product[]>([]),[open,setOpen]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{const raw=localStorage.getItem('n1-products');if(raw)try{setProducts(JSON.parse(raw))}catch{}},[]);
 const cats=['Barchasi',...Array.from(new Set(products.map(x=>x.category)))];
 const shown=useMemo(()=>products.filter(p=>(cat==='Barchasi'||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase())),[products,cat,q]);
 const add=(p:Product)=>{setCart(c=>[...c,p]);setToast(p.name+' savatga qo‘shildi');setTimeout(()=>setToast(''),1800)};
 const total=cart.reduce((s,p)=>s+p.price,0);
 return <><div className="topbar"><div className="container"><span>⚡ 30 daqiqada yetkazib berish</span><span>Har kuni 10:00 — 02:00 · Toshkent</span></div></div>
 <nav className="nav"><div className="container navin"><div className="logo">Lavash<span>N1</span></div><div className="navlinks"><a href="#menu">Menyu</a><a href="#why">Nega biz?</a><a href="#delivery">Yetkazib berish</a></div><div className="actions"><div className="iconbtn"><Search size={19}/></div><button className="iconbtn cart" onClick={()=>setOpen(true)}><ShoppingBag size={20}/>{cart.length>0&&<b className="badge">{cart.length}</b>}</button></div></div></nav>
 <main><section className="hero"><div className="container"><div className="heroBox"><div><div className="eyebrow">LAVASH N1 · ORIGINAL TA’M</div><h1>Och qoldingmi? N1 ni tanla.</h1><p>Sevimli lavash, burger va setlaringizni bir necha bosishda buyurtma qiling. Issiq, mazali va tez.</p><button className="cta" onClick={()=>document.getElementById('menu')?.scrollIntoView()}>Menyuni ko‘rish <ChevronRight size={18}/></button></div><img className="heroDish" src={products[0]?.image} alt="Lavash N1"/></div></div></section>
 <section className="section" id="menu"><div className="container"><div className="sectionHead"><div><div className="muted">Bugungi tanlov</div><h2>Eng ko‘p buyurtma qilinadiganlar</h2></div><div style={{display:'flex',gap:8,alignItems:'center'}}><Search size={18}/><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Taom qidirish..."/></div></div><div className="chips">{cats.map(c=><button key={c} className={'chip '+(cat===c?'active':'')} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="products" style={{marginTop:22}}>{shown.map(p=><article className="card" key={p.id}><img className="foodimg" src={p.image} alt={p.name}/><div className="cardbody"><div className="rating"><Star size={12} fill="currentColor" style={{verticalAlign:'-2px'}}/> {p.rating}</div><h3>{p.name}</h3><p>{p.desc}</p><div className="row"><span className="price">{money(p.price)}</span><button className="add" onClick={()=>add(p)}><Plus size={17}/></button></div></div></article>)}</div>{shown.length===0&&<div className="empty">Bu nomdagi taom topilmadi.</div>}</div></section>
 <section className="section" id="why"><div className="container"><div className="sectionHead"><div><div className="muted">N1 farqi</div><h2>Nega aynan Lavash N1?</h2></div></div><div className="features"><div className="feature"><div className="featureIcon"><Truck/></div><h3>Tez yetkazib berish</h3><p>Buyurtmangizni issiq holda imkon qadar tez yetkazamiz.</p></div><div className="feature"><div className="featureIcon"><ShieldCheck/></div><h3>Sifat kafolati</h3><p>Yangi mahsulotlar, nazorat qilingan tayyorlash jarayoni.</p></div><div className="feature"><div className="featureIcon"><Heart/></div><h3>Mehr bilan tayyorlanadi</h3><p>Har bir buyurtma siz qayta buyurtma qilishingiz uchun tayyorlanadi.</p></div></div></div></section>
 <section className="section" id="delivery"><div className="container"><div className="feature" style={{background:'#171717',color:'#fff',display:'flex',justifyContent:'space-between',alignItems:'center',gap:20}}><div><div className="eyebrow">YETKAZIB BERISH</div><h2 style={{fontSize:32}}>25–40 daqiqada eshigingizda</h2><p style={{color:'#bbb'}}>Yetkazib berish hududingiz va buyurtma vaqtiga qarab hisoblanadi.</p></div><MapPin size={50}/></div></div></section></main>
 <footer className="footer"><div className="container footerGrid"><div><div className="logo">Lavash<span style={{color:'#fff'}}>N1</span></div><p style={{color:'#aaa'}}>Mazali tanlov. Tez yetkazib berish. N1 tajriba.</p></div><div><b>Foydali</b><a href="#menu">Menyu</a><a href="#why">Nega biz?</a><a href="/n1-control-8472/login">Admin</a></div><div><b>Aloqa</b><a href="tel:+998900000000">+998 90 000 00 00</a><span style={{color:'#aaa'}}>Toshkent shahri</span></div></div></footer>
 {open&&<div className="cartDrawer" onClick={()=>setOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><h2>Savat</h2><button className="iconbtn" onClick={()=>setOpen(false)}><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag size={42}/><p>Savatingiz hozircha bo‘sh.</p></div>:<>{cart.map((p,i)=><div className="cartItem" key={i}><img src={p.image} alt=""/><div><b>{p.name}</b><div className="muted">{money(p.price)}</div></div><button className="smallBtn" onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><Minus size={15}/></button></div>)}<div style={{marginTop:25}}><div className="row" style={{marginBottom:14}}><b>Jami</b><b className="price">{money(total)}</b></div><button className="checkout" onClick={()=>{alert('Buyurtma qabul qilindi! Tez orada operator bog‘lanadi.');setCart([]);setOpen(false)}}>Buyurtma berish</button></div></>}</aside></div>}
 {toast&&<div style={{position:'fixed',right:20,bottom:20,zIndex:90,background:'#171717',color:'#fff',padding:'13px 18px',borderRadius:13,fontWeight:800}}>{toast}</div>}</>
}