'use client';
import { useEffect,useMemo,useState } from 'react';
import { Search,ShoppingBag,MapPin,Clock,Star,Plus,Minus,X,Phone,ChevronRight,Flame,Truck,ShieldCheck,Heart } from 'lucide-react';

type Product={id:number,name:string,description:string,price:number,oldPrice?:number|null,image:string,popular:boolean,featured:boolean,prepMinutes:number,rating:number,categoryId:number};
type Category={id:number,name:string,slug:string,icon:string,products:Product[]};
type Data={categories:Category[],banners:any[],settings:Record<string,string>};
type CartItem={product:Product,quantity:number};
const money=(n:number)=>`${new Intl.NumberFormat('uz-UZ').format(n)} so‘m`;

export default function Store(){
 const [data,setData]=useState<Data|null>(null),[active,setActive]=useState('all'),[q,setQ]=useState(''),[cart,setCart]=useState<CartItem[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{fetch('/api/public/menu').then(r=>{if(!r.ok)throw new Error('Menyu yuklanmadi');return r.json()}).then(setData).catch(()=>setData({categories:[],banners:[],settings:{}})); const saved=localStorage.getItem('n1-cart'); if(saved) try{setCart(JSON.parse(saved))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('n1-cart',JSON.stringify(cart))},[cart]);
 const products=useMemo(()=>data?.categories.flatMap(c=>c.products)||[],[data]);
 const shown=products.filter(p=>(active==='all'||data?.categories.find(c=>c.id===p.categoryId)?.slug===active)&&(`${p.name} ${p.description}`.toLowerCase().includes(q.toLowerCase())));
 const count=cart.reduce((s,x)=>s+x.quantity,0), subtotal=cart.reduce((s,x)=>s+x.product.price*x.quantity,0);
 const add=(p:Product)=>setCart(c=>{const e=c.find(x=>x.product.id===p.id); return e?c.map(x=>x.product.id===p.id?{...x,quantity:Math.min(20,x.quantity+1)}:x):[...c,{product:p,quantity:1}]});
 const change=(id:number,d:number)=>setCart(c=>c.map(x=>x.product.id===id?{...x,quantity:x.quantity+d}:x).filter(x=>x.quantity>0));
 const place=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setNotice(''); const fd=new FormData(e.currentTarget); const payload={customer:fd.get('customer'),phone:fd.get('phone'),address:fd.get('address'),comment:fd.get('comment'),payment:fd.get('payment'),promoCode:fd.get('promoCode'),items:cart.map(x=>({productId:x.product.id,quantity:x.quantity}))}; try{const r=await fetch('/api/public/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok){setNotice(j.error||'Xatolik');return;} setCart([]);setCheckout(false);setCartOpen(false);location.href=`/order/${j.code}`;}catch{setNotice('Internet yoki server xatosi. Qayta urinib ko‘ring.')}finally{setBusy(false)}};
 if(!data)return <div className="loading"><div className="spinner"/><b>Lavash N1 yuklanmoqda...</b></div>;
 const hero=data.banners[0];
 return <main>
   <header className="nav"><div className="wrap navin"><a className="brand" href="#top"><span>N1</span> Lavash N1</a><nav><a href="#menu">Menyu</a><a href="#why">Nega biz?</a><a href="#contact">Aloqa</a></nav><button className="cartBtn" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><b>{count}</b><span>Savat</span></button></div></header>
   <section id="top" className="hero"><div className="wrap heroGrid"><div className="heroText"><div className="pill"><Flame size={16}/> Toshkentda mazali yetkazib berish</div><h1>Ochlikka <em>N1</em> yechim.</h1><p>{hero?.subtitle||'Issiq lavash, burger va setlar. Tez tayyorlaymiz, chiroyli qadoqlaymiz, manzilingizgacha olib boramiz.'}</p><div className="heroActions"><a className="primary" href="#menu">Buyurtma berish <ChevronRight size={20}/></a><a className="secondary" href={`tel:${data.settings.phone||''}`}><Phone size={18}/> {data.settings.phone||'+998 90 777 11 11'}</a></div><div className="stats"><div><b>4.9</b><span>mijozlar bahosi</span></div><div><b>25–35 daq</b><span>o‘rtacha yetkazish</span></div><div><b>{data.settings.workingHours||'10:00–02:00'}</b><span>har kuni ishlaymiz</span></div></div></div><div className="heroCard"><div className="glow"/>{hero?.image&&<img src={hero.image} alt="Lavash N1"/>}<div className="float f1"><Star size={18} fill="currentColor"/> 4.9 reyting</div><div className="float f2"><Truck size={18}/> Tez yetkazish</div></div></div></section>
   <section className="quick wrap"><div><MapPin/><span><b>Manzil</b>{data.settings.address||'Toshkent shahri bo‘ylab'}</span></div><div><Clock/><span><b>Ish vaqti</b>{data.settings.workingHours||'10:00 — 02:00'}</span></div><div><ShieldCheck/><span><b>Sifat</b>Har kuni yangi mahsulot</span></div></section>
   <section id="menu" className="menuSec"><div className="wrap"><div className="secHead"><div><span className="eyebrow">MENYU</span><h2>Bugun nima yeysiz?</h2></div><div className="search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Taom qidirish..."/></div></div><div className="cats"><button className={active==='all'?'on':''} onClick={()=>setActive('all')}>🔥 Barchasi</button>{data.categories.map(c=><button key={c.id} className={active===c.slug?'on':''} onClick={()=>setActive(c.slug)}>{c.icon} {c.name}</button>)}</div><div className="products">{shown.map(p=><article className="product" key={p.id}><div className="pic"><img src={p.image} alt={p.name}/>{p.popular&&<span className="tag">TOP</span>}<button className="heart" aria-label="Sevimli"><Heart size={18}/></button></div><div className="pbody"><div className="meta"><span><Star size={15} fill="currentColor"/>{p.rating}</span><span><Clock size={15}/>{p.prepMinutes} daq</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="pfoot"><div><b>{money(p.price)}</b>{p.oldPrice&&<s>{money(p.oldPrice)}</s>}</div><button onClick={()=>add(p)}><Plus size={20}/> Qo‘shish</button></div></div></article>)}</div>{!shown.length&&<div className="empty">Hech narsa topilmadi. Boshqa so‘z bilan qidiring.</div>}</div></section>
   <section id="why" className="why"><div className="wrap"><span className="eyebrow">N1 STANDARTI</span><h2>Oddiy fast food emas.</h2><div className="whyGrid"><div><span>01</span><h3>Yangi tayyorlanadi</h3><p>Buyurtmangiz kelgandan keyin tayyorlashni boshlaymiz. Issiq va mazali holatda yetib boradi.</p></div><div><span>02</span><h3>Tez yetkazamiz</h3><p>Hudud bo‘yicha buyurtmalar oqimini boshqaramiz va yo‘lda vaqtni kamaytiramiz.</p></div><div><span>03</span><h3>Halol narx</h3><p>Narxlar so‘mda va yashirin qo‘shimchalarsiz. Savatda yakuniy hisobni ko‘rasiz.</p></div></div></div></section>
   <footer id="contact"><div className="wrap foot"><div><a className="brand dark" href="#top"><span>N1</span> Lavash N1</a><p>Mazali. Tez. N1.</p></div><div><b>Aloqa</b><a href={`tel:${data.settings.phone||''}`}>{data.settings.phone||'+998 90 777 11 11'}</a><span>{data.settings.address||'Toshkent shahri'}</span></div><div><b>Ish vaqti</b><span>{data.settings.workingHours||'10:00 — 02:00'}</span><span>Har kuni</span></div></div><div className="wrap copy">© 2026 Lavash N1. Barcha huquqlar himoyalangan.</div></footer>
   {count>0&&<button className="mobileCart" onClick={()=>setCartOpen(true)}><ShoppingBag/> <b>{count} ta</b><span>{money(subtotal)}</span></button>}
   {cartOpen&&<div className="overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setCartOpen(false)}}><aside className="drawer"><div className="drawerHead"><div><span>Sizning savatingiz</span><h2>{count} ta mahsulot</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="cartItems">{cart.map(x=><div className="cartItem" key={x.product.id}><img src={x.product.image} alt=""/><div className="cartInfo"><b>{x.product.name}</b><span>{money(x.product.price)}</span><div className="qty"><button onClick={()=>change(x.product.id,-1)}><Minus size={16}/></button><b>{x.quantity}</b><button onClick={()=>change(x.product.id,1)}><Plus size={16}/></button></div></div><b>{money(x.product.price*x.quantity)}</b></div>)}{!cart.length&&<div className="empty">Savat hozircha bo‘sh.</div>}</div>{cart.length>0&&<div className="cartBottom"><div><span>Mahsulotlar</span><b>{money(subtotal)}</b></div><small>Yetkazish narxi va chegirma checkoutda aniq hisoblanadi.</small><button className="primary full" onClick={()=>setCheckout(true)}>Rasmiylashtirish <ChevronRight/></button></div>}</aside></div>}
   {checkout&&<div className="overlay"><div className="modal"><button className="modalX" onClick={()=>setCheckout(false)}><X/></button><span className="eyebrow">BUYURTMA</span><h2>Yetkazib berish ma’lumotlari</h2><form onSubmit={place}><label>Ismingiz<input name="customer" required placeholder="Ism"/></label><label>Telefon<input name="phone" required placeholder="+998 90 123 45 67"/></label><label>Manzil<textarea name="address" required placeholder="Ko‘cha, uy, mo‘ljal"/></label><div className="formRow"><label>Promo-kod<input name="promoCode" placeholder="N1START"/></label><label>To‘lov<select name="payment"><option>Naqd</option><option>Karta orqali kuryerga</option></select></label></div><label>Izoh<textarea name="comment" placeholder="Masalan: piyozsiz..."/></label>{notice&&<div className="alert">{notice}</div>}<button disabled={busy} className="primary full">{busy?'Yuborilmoqda...':`Buyurtma berish · ${money(subtotal)}`}</button></form></div></div>}
 </main>
}
